# Travis CI (http://travis-ci.org/) is a continuous integration service for
# open source projects. This file configures it to run unit tests for
# ase.

language: go

go:
    - 1.2
    - 1.3
    - 1.4

script:
    - go test -v ./...